#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SegmentedControl.Android.Resource", IsApplication=true)]

namespace SegmentedControl.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int lineColor = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int lineHeightSelected = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int lineHeightUnselected = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int segmentedControlOptionStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int highlight = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int light = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int normal = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int segmented_control_text = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int selected = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int segmented_control_default_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int segmented_control_text_size = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int segmented_control_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int segmented_control_first_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int segmented_control_last_background = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int myButton = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int radioFemale = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int radioMale = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int radioSex = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SegmentedControl = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CustomTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int SegmentedControlOption = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SegmentedControlOption = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int SegmentedControlOption_lineColor = 1;
			
			// aapt resource value: 3
			public const int SegmentedControlOption_lineHeightSelected = 3;
			
			// aapt resource value: 2
			public const int SegmentedControlOption_lineHeightUnselected = 2;
			
			// aapt resource value: 0
			public const int SegmentedControlOption_segmentedControlOptionStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
